language: generic
sudo: required
services:
  - docker

script:
  - docker build -t mozilla/hindsight:latest .

deploy:
  - provider: script
    script: bash docker_push.sh $TRAVIS_BRANCH
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^dev|master$
